Blog post: introducing KW 1.11
kubewarden/kubewarden.io pull request #217
Opened 2024-03-14 10:03 UTC by flavio

Fixes https://github.com/kubewarden/kubewarden.io/issues/215

2024-03-14 12:29 UTC, jvanz approved these changes

2024-03-14 13:05 UTC, fabriziosestito commented on content/blog/2024/03/kubewarden-1-11-release.md
> +This release focused on performance improvements, especially when running on big Kubernetes clusters.
focuses

2024-03-14 13:08 UTC, fabriziosestito requested changes

2024-03-14 13:32 UTC, flavio commented on content/blog/2024/03/kubewarden-1-11-release.md
> +This release focused on performance improvements, especially when running on big Kubernetes clusters.
done

2024-03-14 13:32 UTC, flavio commented on content/blog/2024/03/kubewarden-1-11-release.md
> +This solution proved to not scale inside of clusters with many audited resources. That's why, starting from Kubewarden 1.11, the audit scanner
I've expanded on that, please take another look

2024-03-14 14:00 UTC, jhkrug requested changes
A few changes suggested, but lgtm.

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +Moreover, the amount of memory required by the audit scanner could be significant.
```suggestion
We've also changed how we handle Policy Reports. Kubewarden is still using the Policy Report format being defined inside the Kubernetes's `wg-policy` group. However, prior to this release,
we used to create one `PolicyReport` per `Namespace` and one `ClusterPolicyReport` per cluster.
This solution proved to not scale inside clusters with many audited resources. Depending on the number of policies and audited resources, the size of the final report objects could be too big to fit into etcd.
Moreover, the amount of memory required by the audit scanner could be significant.
```

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +policies and resources being audited.
```suggestion
That's why, starting from Kubewarden 1.11, the audit scanner creates one `PolicyReport` per namespaced resource and one `ClusterPolicyReport` per cluster-wide resource being scanned.
That ensures the reports can always fit etcd's size requirement. On top of that, now the audit scanner process always consumes the same amount of memory, regardless of the number of
policies and resources being audited.
```

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +Getting the auditing results of the resources defined inside of a namespace can be done in this way:
```suggestion
Getting the auditing results of the resources defined inside a namespace can be done in this way:
```

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +This addition was requested by our community as a way to write policies that make use of the platform and architecture information found inside of the OCI manifest to make mutations.
```suggestion
Kubewarden 1.11 expands the operations that can be done against a container registry by making it possible to fetch OCI manifests.
This addition was requested by our community as a way to write policies that make use of the platform and architecture information found inside the OCI manifest to make mutations.
```

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +First, the load on the Kubernetes API server is reduced. Second, the information shared with the policies is significantly fresher than before. That means changes done inside of Kubernetes are propag
```suggestion
Starting from the 1.11 release, Kubewarden uses a different way to fetch information from the Kubernetes API server and keep this data up to date. That brings two major improvements.
Firstly, the load on the Kubernetes API server is reduced. Secondly, the information shared with the policies is significantly fresher than before. That means changes done inside Kubernetes are propagated faster to
```

2024-03-14 14:00 UTC, jhkrug commented on content/blog/2024/03/kubewarden-1-11-release.md
> +We started an [investigation](https://github.com/kubewarden/policy-server/issues/692) that lead to several performance improvements that are now part of the Kubewarden 1.11 release.
```suggestion
We started an [investigation](https://github.com/kubewarden/policy-server/issues/692) that led to several performance improvements that are now part of the Kubewarden 1.11 release.
```

2024-03-14 15:26 UTC, flavio commented
@jhkrug thanks a lot for the fixes, I've included all of them

2024-03-14 16:24 UTC, fabriziosestito approved these changes

2024-03-15 12:13 UTC, jhkrug approved these changes
lgtm

2024-03-15 13:24 UTC, flavio commented
Moving to blocked, waiting for 1.11 to be out

2024-03-21 07:19 UTC, merged