feat: community repository blog post
kubewarden/kubewarden.io pull request #219
Opened 2024-04-04 17:32 UTC by jvanz

## Description

Adds a new blog post to announce the community repository.

Related to https://github.com/kubewarden/kubewarden-controller/issues/659

2024-04-08 06:10 UTC, viccuad requested changes
I would like to have a link to the repo, and maybe just copy the table of contents.

The blogpost content sounds a bit buzzwordy for my liking :). I'm ok with it being shorter.

2024-04-08 12:41 UTC, viccuad approved these changes

2024-04-08 14:29 UTC, flavio approved these changes
Thanks!

2024-04-09 08:48 UTC, fabriziosestito approved these changes

2024-04-09 12:16 UTC, jvanz commented
Moving to block until we decide when to make this post public

2024-04-09 13:43 UTC, merged