Add 1.16 release post
kubewarden/kubewarden.io pull request #257
Opened 2024-08-16 10:47 UTC by viccuad

## Description

Fix https://github.com/kubewarden/kubewarden.io/issues/254

## Test

## Additional Information

### Tradeoff

### Potential improvement

2024-08-16 12:13 UTC, jvanz requested changes
I think we should mention some policies updates. I just noticed that I've forget to update the card with the necessary information. Let me share the most important ones here:

- https://github.com/kubewarden/container-resources-policy/pull/53
- https://github.com/kubewarden/user-group-psp-policy/pull/96

Sorry for sharing this late
-

2024-08-16 13:49 UTC, viccuad commented
@jvanz good point, I totally forgot, thanks! Added them, please re-review.

2024-08-16 22:30 UTC, jhkrug approved these changes
lgtm

2024-08-19 13:40 UTC, jvanz requested changes

2024-08-19 13:40 UTC, jvanz commented on content/blog/2024/08/kubewarden-1-16-release.md
> +container image.
Actually, the container image is not enabled by default. In the `v0.6.2` we fix an issue in the `RunAsAny` rule for the group when the container image validation is enabled. Furthermore, we documented the issue about the timeout due the time that context aware call takes.

2024-08-19 13:41 UTC, jvanz approved these changes

2024-08-19 14:16 UTC, merged